VERSION = 'Version'
IHL = 'IHL'
LEN = 'LEN'
ID = 'ID'
TTL = 'TTL'
CS_IP = 'Chk IP'
CS_TCP = 'Chk TCP'
CS_UDP = 'Chk UDP'
CS_ICMP = 'Chk ICMP'
FRAG = 'FRAG'
CODE = 'CODE'
SP = 'SP'
DP = 'DP'
SEQ = 'Seq'
ACK = 'Ack'
DO = 'DO'
WS = 'WIN'
CHK = 'CHK'
UP = 'UP'
TOS = 'TOS'
FLAGS = 'Flags'
CONTROL_BITS = 'Control bits'
RESERVED = 'Reserved'
TYPE = 'Type'
DATAOFS = 'dataofs'
LEN_UDP = 'Len UDP'
PROTOCOL = 'Protocol'
ADD = 'Add'
CLEAR = 'Clear'
SEND_ALL = 'Send all'

MF = 'MF'
DF = 'DF'
EVIL = 'evil'

SEND = 'Send'
SAVE = 'Save'
OPEN = 'Open'

INTERFACE = 'Interface'
SOURCE_ADDRESS = 'Src'
DESTINATION_ADDRESS = 'Dst'

IP_OPTIONS = 'IP options'
TCP_OPTIONS = 'TCP options'
ICMP_DATA = 'ICMP data'

